<template>
  <q-page class="dashboard-page user-page">
    <div class="page-intro"><div><span class="page-overline">MINHA ROTINA</span><h1>Meus agendamentos</h1><p>Acompanhe horários, detalhes e alterações em um só lugar.</p></div><q-btn to="/barbearia-premium/agendar" rounded unelevated color="dark" no-caps label="Agendar novo horário" icon="add" /></div>
    <q-tabs v-model="tab" align="left" no-caps active-color="dark" indicator-color="lime-6" class="user-tabs"><q-tab name="upcoming" label="Próximos" /><q-tab name="past" label="Histórico" /></q-tabs>
    <div v-if="filtered.length" class="user-appointment-list"><article v-for="item in filtered" :key="item._id" class="panel-card user-appointment"><div class="appointment-date"><span>{{ month(item.start) }}</span><b>{{ day(item.start) }}</b><small>{{ weekday(item.start) }}</small></div><div class="appointment-divider" /><div class="appointment-info"><q-badge rounded :color="statusColor(item.status)" :label="statusLabel(item.status)" /><h3>{{ item.serviceName }}</h3><p><q-icon name="storefront" /> {{ item.profile?.businessName }}</p><p><q-icon name="schedule" /> {{ time(item.start) }} · {{ item.duration }} minutos</p><p v-if="item.profile?.address"><q-icon name="location_on" /> {{ item.profile.address }}</p><div v-if="item.adjustmentRequested" class="adjustment-note"><q-icon name="pending_actions" /> Solicitação de ajuste enviada. Aguarde a confirmação.</div></div><div class="appointment-price"><small>VALOR</small><b>{{ money(item.price) }}</b><q-btn v-if="isUpcoming(item) && item.status !== 'CANCELLED'" flat rounded no-caps label="Solicitar ajuste" icon="edit_calendar" @click="openAdjust(item)" /><q-btn v-if="isUpcoming(item) && item.status !== 'CANCELLED'" flat rounded color="negative" no-caps label="Cancelar" @click="cancel(item)" /></div></article></div>
    <div v-else class="panel-card empty-state"><span><q-icon name="event_available" /></span><h2>{{ tab === 'upcoming' ? 'Sua agenda está livre.' : 'Nenhum atendimento no histórico.' }}</h2><p v-if="tab === 'upcoming'">Escolha um serviço e encontre o melhor horário em poucos toques.</p><q-btn v-if="tab === 'upcoming'" to="/barbearia-premium/agendar" rounded unelevated color="dark" no-caps label="Encontrar um horário" icon-right="arrow_forward" /></div>
    <div v-if="pagination.pages > 1" class="row justify-center q-mt-lg"><q-pagination v-model="pagination.page" :max="pagination.pages" direction-links color="dark" @update:model-value="load" /></div>
    <q-dialog v-model="adjustDialog"><q-card class="appointment-dialog"><q-card-section class="dialog-title"><div><span>SOLICITAR AJUSTE</span><h3>Qual horário funciona melhor?</h3></div><q-btn flat round icon="close" v-close-popup /></q-card-section><q-card-section class="form-stack"><q-input v-model="adjust.proposedStart" outlined rounded type="datetime-local" label="Nova data e horário sugeridos" stack-label /><q-input v-model="adjust.adjustmentNote" outlined rounded type="textarea" autogrow label="Mensagem para o profissional" placeholder="Conte o motivo ou outras opções de horário" /></q-card-section><q-card-actions class="q-pa-md"><q-space /><q-btn flat rounded label="Voltar" no-caps v-close-popup /><q-btn rounded unelevated color="dark" label="Enviar solicitação" no-caps @click="sendAdjust" /></q-card-actions></q-card></q-dialog>
  </q-page>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useQuasar } from 'quasar'
import { api } from 'boot/axios'
const $q = useQuasar(); const tab = ref('upcoming'); const appointments = ref([]); const pagination = ref({ page: 1, pages: 1 }); const adjustDialog = ref(false); const editing = ref(null); const adjust = reactive({ proposedStart: '', adjustmentNote: '' })
const isUpcoming = item => new Date(item.start) > new Date(); const filtered = computed(() => appointments.value.filter(item => tab.value === 'upcoming' ? isUpcoming(item) : !isUpcoming(item)))
const month = value => new Date(value).toLocaleDateString('pt-BR', { month: 'short' }).replace('.', '').toUpperCase(); const day = value => new Date(value).getDate(); const weekday = value => new Date(value).toLocaleDateString('pt-BR', { weekday: 'short' }).replace('.', ''); const time = value => new Date(value).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }); const money = value => Number(value).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }); const statusLabel = value => ({ CONFIRMED: 'Confirmado', PENDING: 'Pendente', COMPLETED: 'Concluído', CANCELLED: 'Cancelado' }[value]); const statusColor = value => ({ CONFIRMED: 'positive', PENDING: 'warning', COMPLETED: 'blue-grey', CANCELLED: 'negative' }[value])
async function load () { const { data } = await api.get('/appointments', { params: { page: pagination.value.page, limit: 20 } }); appointments.value = data.data; pagination.value = data.pagination }
function openAdjust (item) { editing.value = item; Object.assign(adjust, { proposedStart: '', adjustmentNote: '' }); adjustDialog.value = true }
async function sendAdjust () { await api.patch(`/appointments/${editing.value._id}`, adjust); $q.notify({ type: 'positive', message: 'Solicitação enviada ao profissional.' }); adjustDialog.value = false; load() }
function cancel (item) { $q.dialog({ title: 'Cancelar agendamento?', message: 'O horário será liberado para outra pessoa.', cancel: true, persistent: true }).onOk(async () => { await api.patch(`/appointments/${item._id}`, { status: 'CANCELLED' }); $q.notify({ message: 'Agendamento cancelado.', color: 'dark' }); load() }) }
onMounted(load)
</script>
