<template>
  <q-page class="dashboard-page profile-page">
    <div class="page-intro"><div><span class="page-overline">MINHA CONTA</span><h1>Dados pessoais</h1><p>Mantenha seus contatos atualizados para facilitar seus agendamentos.</p></div><q-btn rounded unelevated color="dark" no-caps label="Salvar alterações" icon="save" :loading="saving" @click="save" /></div>
    <div class="profile-grid"><section class="panel-card avatar-card"><div class="avatar-upload"><q-avatar size="116px" color="grey-3" text-color="dark"><img v-if="form.avatar" :src="form.avatar"><span v-else>{{ initials }}</span></q-avatar><q-btn round unelevated color="dark" icon="photo_camera" class="avatar-button"><q-file class="absolute-full transparent-file" borderless accept="image/*" @update:model-value="uploadAvatar" /></q-btn></div><h3>{{ auth.user?.name }}</h3><p>Cliente CortsMe</p><q-badge rounded color="lime-5" text-color="dark" label="Conta protegida" /><q-separator spaced /><small>Você também pode usar uma imagem por link:</small><q-input v-model="form.avatar" outlined rounded dense label="URL do avatar" class="full-width q-mt-sm" /></section><section class="panel-card profile-form-card"><div class="panel-heading"><div><span>INFORMAÇÕES</span><h3>Seu perfil</h3></div></div><div class="form-stack"><q-input v-model="form.name" outlined rounded label="Nome completo"><template #prepend><q-icon name="person_outline" /></template></q-input><q-input v-model="form.email" outlined rounded label="E-mail"><template #prepend><q-icon name="alternate_email" /></template></q-input><q-input v-model="form.phone" outlined rounded label="Telefone" mask="(##) #####-####" unmasked-value><template #prepend><q-icon name="phone_iphone" /></template></q-input><q-separator spaced /><h4>Alterar senha</h4><q-input v-model="form.password" outlined rounded type="password" label="Nova senha (opcional)" hint="Use pelo menos 8 caracteres"><template #prepend><q-icon name="lock_outline" /></template></q-input><div class="privacy-box"><q-icon name="encrypted" /><div><b>Seus dados ficam protegidos</b><p>Contato cifrado no banco e usado apenas para sua conta e agendamentos.</p></div></div></div></section></div>
  </q-page>
</template>

<script setup>
import { computed, reactive, ref } from 'vue'
import { useQuasar } from 'quasar'
import { api } from 'boot/axios'
import { useAuthStore } from 'stores/auth-store'
const auth = useAuthStore(); const $q = useQuasar(); const saving = ref(false); const form = reactive({ name: auth.user?.name || '', email: auth.user?.email || '', phone: auth.user?.phone || '', avatar: auth.user?.avatar || '', password: '' }); const initials = computed(() => auth.user?.name?.split(' ').slice(0, 2).map(item => item[0]).join('').toUpperCase())
async function uploadAvatar (file) { if (!file) return; const data = new FormData(); data.append('image', file); try { const response = await api.post('/auth/avatar', data); form.avatar = response.data.url; auth.updateUser(response.data.user); $q.notify({ type: 'positive', message: 'Foto atualizada.' }) } catch (error) { $q.notify({ type: 'negative', message: error.response?.data?.message || 'Falha no upload.' }) } }
async function save () { saving.value = true; try { const payload = { ...form }; if (!payload.password || auth.user?.provider === 'google') delete payload.password; const { data } = await api.patch('/auth/me', payload); if (data.token) auth.setSession(data); else auth.updateUser(data.user); form.password = ''; $q.notify({ type: 'positive', message: auth.user?.provider === 'google' ? 'Perfil atualizado. Sua senha continua gerenciada pelo Google.' : 'Perfil atualizado.' }) } catch (error) { $q.notify({ type: 'negative', message: error.response?.data?.message || 'Não foi possível salvar.' }) } finally { saving.value = false } }
</script>
