<template>
  <q-page class="dashboard-page" v-if="profile">
    <div class="page-intro"><div><span class="page-overline">ATENDIMENTO INTELIGENTE</span><h1>Bot assistente</h1><p>Ensine seu assistente e acompanhe o que seus clientes perguntam.</p></div><div class="row items-center q-gutter-sm"><q-toggle v-model="profile.bot.enabled" color="positive" :label="profile.bot.enabled ? 'Bot ativo' : 'Bot pausado'" /><q-btn rounded unelevated color="dark" no-caps label="Salvar configurações" icon="save" :loading="saving" @click="save" /></div></div>
    <div class="bot-config-grid"><section class="panel-card bot-config"><div class="panel-heading"><div><span>PERSONALIDADE</span><h3>Como o bot conversa</h3></div><span class="online-chip"><i /> Aprendendo com seu negócio</span></div><div class="form-stack"><q-input v-model="profile.bot.name" outlined rounded label="Nome do assistente" /><q-input v-model="profile.bot.greeting" outlined rounded type="textarea" autogrow label="Saudação inicial" counter maxlength="260" /><q-input v-model="profile.bot.relevantInfo" outlined rounded type="textarea" autogrow label="Informações importantes" hint="Políticas, estacionamento, diferenciais, formas de pagamento..." /><div class="bot-map-setting"><span class="quick-icon lime"><q-icon name="map" /></span><div><b>Mapa na conversa</b><small>{{ profile.site.locationMap?.embedUrl ? 'Mostra o mapa quando o cliente perguntar como chegar.' : 'Configure o iframe em Meu Site → Link.' }}</small></div><q-toggle v-model="profile.site.locationMap.botEnabled" color="positive" :disable="!profile.site.locationMap?.embedUrl" /></div><label>MENU RÁPIDO</label><div v-for="(option, index) in profile.bot.menuOptions" :key="index" class="option-row"><q-icon name="drag_indicator" /><q-input v-model="profile.bot.menuOptions[index]" dense borderless class="col" /><q-btn flat round dense icon="close" @click="profile.bot.menuOptions.splice(index, 1)" /></div><q-btn v-if="profile.bot.menuOptions.length < 6" outline rounded no-caps icon="add" label="Adicionar opção" @click="profile.bot.menuOptions.push('Nova opção')" /></div></section>
      <section class="panel-card bot-preview-card"><div class="panel-heading"><div><span>PRÉVIA</span><h3>Conversa no site</h3></div></div><div class="bot-phone-preview"><div class="bot-header"><div class="row items-center"><q-avatar color="lime-5" text-color="dark" icon="smart_toy" /><div class="q-ml-sm"><b>{{ profile.bot.name }}</b><small><span class="online-dot" /> Online agora</small></div></div></div><div class="bot-messages"><div class="bot-message bot"><div>{{ profile.bot.greeting }}</div></div></div><div class="bot-suggestions"><button v-for="option in profile.bot.menuOptions.slice(0, 4)" :key="option">{{ option }}</button></div><div class="bot-input"><input disabled placeholder="Digite sua dúvida..."><q-btn round unelevated color="dark" icon="arrow_upward" /></div></div></section>
    </div>
    <section class="panel-card q-mt-lg"><div class="panel-heading"><div><span>CONVERSAS RECENTES</span><h3>Logs de interação</h3></div><q-btn flat rounded icon="refresh" no-caps label="Atualizar" @click="loadLogs" /></div><q-table flat :rows="logs" :columns="columns" row-key="_id" :loading="loadingLogs" hide-pagination><template #body-cell-intent="props"><q-td :props="props"><q-badge rounded color="grey-3" text-color="dark" :label="intentLabel(props.value)" /></q-td></template><template #body-cell-createdAt="props"><q-td :props="props">{{ dateTime(props.value) }}</q-td></template></q-table><div class="table-footer"><span>{{ pagination.total }} interações</span><q-pagination v-model="pagination.page" :max="pagination.pages" color="dark" direction-links @update:model-value="loadLogs" /></div></section>
  </q-page>
</template>

<script setup>
import { onMounted, ref } from 'vue'
import { useQuasar } from 'quasar'
import { api } from 'boot/axios'
const $q = useQuasar(); const profile = ref(null); const saving = ref(false); const logs = ref([]); const loadingLogs = ref(false); const pagination = ref({ page: 1, pages: 1, total: 0 })
const columns = [{ name: 'message', label: 'Pergunta do cliente', field: 'message', align: 'left' }, { name: 'response', label: 'Resposta', field: 'response', align: 'left' }, { name: 'intent', label: 'Intenção', field: 'intent', align: 'left' }, { name: 'createdAt', label: 'Quando', field: 'createdAt', align: 'right' }]
const dateTime = value => new Date(value).toLocaleString('pt-BR', { dateStyle: 'short', timeStyle: 'short' }); const intentLabel = value => ({ booking: 'Agendamento', services: 'Serviços', location: 'Localização', faq: 'Dúvida frequente', question: 'Informação' }[value] || value)
async function loadLogs () { loadingLogs.value = true; const { data } = await api.get('/barber/bot/logs', { params: { page: pagination.value.page, limit: 8 } }); logs.value = data.data; pagination.value = data.pagination; loadingLogs.value = false }
async function save () { saving.value = true; try { profile.value = (await api.put('/barber/profile', { bot: profile.value.bot, site: profile.value.site })).data.profile; $q.notify({ type: 'positive', message: 'Assistente atualizado.' }) } finally { saving.value = false } }
onMounted(async () => { profile.value = (await api.get('/barber/profile')).data.profile; profile.value.site.locationMap ||= { enabled: false, botEnabled: false, embedUrl: '', title: 'Onde estamos', subtitle: '' }; loadLogs() })
</script>
