<template>
  <q-page class="dashboard-page" v-if="profile">
    <div class="page-intro"><div><span class="page-overline">CONFIGURAÇÕES</span><h1>Seu negócio</h1><p>Serviços, horários e integrações usados pelo site, agenda e bot.</p></div><q-btn rounded unelevated color="dark" no-caps label="Salvar alterações" icon="save" :loading="saving" @click="save" /></div>
    <div class="settings-grid">
      <section class="panel-card settings-card professional-account-card">
        <div class="panel-heading"><div><span>MINHA CONTA</span><h3>Foto do profissional</h3></div><q-badge rounded color="lime-5" text-color="dark" :label="auth.user?.provider === 'google' ? 'Google' : 'E-mail e senha'" /></div>
        <div class="professional-avatar-row">
          <div class="professional-avatar">
            <q-avatar size="88px" color="grey-3" text-color="dark"><img v-if="auth.user?.avatar" :src="auth.user.avatar" alt="Foto do profissional"><span v-else>{{ initials }}</span></q-avatar>
            <q-btn round unelevated color="dark" icon="photo_camera" :loading="avatarLoading" aria-label="Enviar foto do profissional"><q-file class="absolute-full transparent-file" borderless accept="image/jpeg,image/png,image/webp" :max-file-size="4194304" @update:model-value="uploadAvatar" @rejected="avatarRejected" /></q-btn>
          </div>
          <div class="professional-account-fields">
            <q-input v-model.trim="account.name" outlined rounded label="Seu nome" />
            <q-input v-model.trim="account.phone" outlined rounded type="tel" label="Telefone principal da conta" hint="DDD + número; o nono dígito é preservado"><template #prepend><q-icon name="phone_iphone" /></template></q-input>
            <q-input v-model.trim="account.avatarUrl" outlined rounded label="Ou use uma URL HTTPS" placeholder="https://exemplo.com/foto.jpg"><template #prepend><q-icon name="link" /></template></q-input>
            <q-input v-model.trim="account.whatsappMetaPhone" outlined rounded type="tel" label="Número alternativo do WhatsApp Meta (opcional)" placeholder="+556181748795" hint="Use E.164 brasileiro. Se preenchido, somente os envios WhatsApp usam este número."><template #prepend><q-icon name="chat" /></template></q-input>
            <div class="professional-avatar-actions"><q-btn outline rounded no-caps icon="check" label="Usar URL" :disable="avatarLoading" @click="applyAvatarUrl" /><q-btn v-if="auth.user?.avatar" flat rounded no-caps color="negative" icon="delete_outline" label="Remover foto" :disable="avatarLoading" @click="removeAvatar" /></div>
          </div>
        </div>
        <p class="avatar-safety"><q-icon name="shield" /> JPEG, PNG ou WebP, até 4 MB. O arquivo fica vinculado apenas à sua conta profissional.</p>
      </section>
      <section class="panel-card settings-card"><div class="panel-heading"><div><span>INFORMAÇÕES</span><h3>Perfil da barbearia</h3></div></div><div class="form-stack"><q-input v-model="profile.businessName" outlined rounded label="Nome do negócio" /><q-input v-model="profile.description" outlined rounded type="textarea" autogrow label="Descrição" /><q-input v-model="profile.address" outlined rounded label="Endereço" icon="location_on" /><q-input v-model="profile.whatsapp" outlined rounded label="WhatsApp público do negócio" prefix="+" hint="Exibido ao cliente; não substitui o destino dos alertas da conta" /></div></section>
      <section class="panel-card settings-card services-card"><div class="panel-heading"><div><span>CATÁLOGO</span><h3>Serviços</h3></div><q-btn flat round icon="add" @click="addService" /></div><div class="service-editor" v-for="(service, index) in profile.services" :key="service._id || index"><div class="row items-center"><q-toggle v-model="service.active" color="positive" /><q-input v-model="service.name" dense borderless class="col text-weight-medium" /><q-btn flat round dense icon="delete_outline" @click="profile.services.splice(index, 1)" /></div><q-input v-model="service.description" outlined rounded dense label="Descrição" /><div class="row q-col-gutter-sm"><q-input v-model.number="service.duration" outlined rounded dense type="number" suffix="min" class="col" /><q-input v-model.number="service.price" outlined rounded dense type="number" prefix="R$" class="col" /></div></div></section>
      <section class="panel-card settings-card hours-card"><div class="panel-heading"><div><span>DISPONIBILIDADE</span><h3>Horários de funcionamento</h3></div></div><div class="hour-row" v-for="hour in sortedHours" :key="hour.weekday"><q-toggle v-model="hour.enabled" color="positive" /><b>{{ days[hour.weekday] }}</b><template v-if="hour.enabled"><q-input v-model="hour.start" dense outlined rounded type="time" /><span>até</span><q-input v-model="hour.end" dense outlined rounded type="time" /><small>Pausa</small><q-input v-model="hour.breakStart" dense outlined rounded type="time" /><span>—</span><q-input v-model="hour.breakEnd" dense outlined rounded type="time" /></template><span v-else class="closed-label">Fechado</span></div></section>
      <section class="panel-card settings-card reminder-card"><div class="panel-heading"><div><span>NOTIFYFLOW</span><h3>Lembretes automáticos</h3></div><q-toggle v-model="reminders.enabled" color="positive" aria-label="Ativar lembretes" /></div><div class="reminder-body"><p class="settings-copy">Escolha quando e por quais canais o CortsMe deve avisar você e seus clientes.</p><q-select v-model="reminders.channels" :options="channelOptions" emit-value map-options multiple use-chips outlined rounded label="Canais de entrega" :disable="!reminders.enabled" hint="Somente WhatsApp e Gmail" /><div class="morning-reminder"><div><q-toggle v-model="reminders.morningEnabled" color="positive" :disable="!reminders.enabled" label="Resumo diário do barbeiro" /><small>Lista dos agendamentos do dia e link rápido para o calendário.</small></div><q-input v-model="reminders.morningTime" outlined rounded dense type="time" stack-label label="Horário" :disable="!reminders.enabled || !reminders.morningEnabled" /></div><q-select v-model="reminders.timezone" :options="timezoneOptions" outlined rounded emit-value map-options label="Fuso horário" :disable="!reminders.enabled" /><div class="reminder-toggles"><q-toggle v-model="reminders.customerRemindersEnabled" color="positive" :disable="!reminders.enabled" label="Clientes: 24h e 1h antes" /><q-toggle v-model="reminders.billingRemindersEnabled" color="positive" :disable="!reminders.enabled" label="Financeiro: 7 e 1 dia antes" /></div><div class="reminder-safety"><q-icon name="shield" /><span>Cada envio é isolado por barbearia. Contatos e dados de agenda nunca são compartilhados entre profissionais.</span></div></div></section>
      <section class="panel-card settings-card"><div class="panel-heading"><div><span>AUTOMAÇÕES</span><h3>Webhook</h3></div></div><p class="settings-copy">Receba um POST sempre que um agendamento for criado ou atualizado.</p><q-input v-model="profile.webhookUrl" outlined rounded label="URL do webhook" placeholder="https://seu-sistema.com/webhook" /><div class="webhook-info"><q-icon name="bolt" /><span>Eventos enviados: <b>appointment.created</b>, <b>appointment.updated</b> e <b>appointment.deleted</b>.</span></div></section>
    </div>
  </q-page>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useQuasar } from 'quasar'
import { api } from 'boot/axios'
import { useAuthStore } from 'stores/auth-store'
const $q = useQuasar(); const auth = useAuthStore(); const profile = ref(null); const saving = ref(false); const avatarLoading = ref(false); const days = ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado']
const account = reactive({
  name: auth.user?.name || '',
  phone: auth.user?.phone || '',
  whatsappMetaPhone: auth.user?.whatsappMetaPhone || '',
  avatarUrl: auth.user?.avatarSource === 'url' ? auth.user.avatar : ''
})
const reminders = reactive({ enabled: true, channels: ['whatsapp_cloud', 'email'], morningEnabled: true, morningTime: '07:00', timezone: 'America/Sao_Paulo', customerRemindersEnabled: true, billingRemindersEnabled: true })
const channelOptions = [{ label: 'WhatsApp', value: 'whatsapp_cloud' }, { label: 'Gmail', value: 'email' }]
const timezoneOptions = [{ label: 'Brasília / São Paulo', value: 'America/Sao_Paulo' }, { label: 'Manaus', value: 'America/Manaus' }, { label: 'Cuiabá', value: 'America/Cuiaba' }, { label: 'Rio Branco', value: 'America/Rio_Branco' }, { label: 'Fernando de Noronha', value: 'America/Noronha' }]
const sortedHours = computed(() => [...(profile.value?.businessHours || [])].sort((a, b) => (a.weekday === 0 ? 7 : a.weekday) - (b.weekday === 0 ? 7 : b.weekday)))
const initials = computed(() => auth.user?.name?.split(' ').slice(0, 2).map(part => part[0]).join('').toUpperCase() || 'CM')
function addService () { profile.value.services.push({ name: 'Novo serviço', description: '', duration: 30, price: 0, active: true }) }
function avatarRejected () { $q.notify({ type: 'negative', message: 'Use uma imagem JPEG, PNG ou WebP de até 4 MB.' }) }
function validAvatarUrl (value) { try { return new URL(value).protocol === 'https:' } catch { return false } }
function validPrimaryPhone (value) { const digits = String(value || '').replace(/\D/g, ''); return [10, 11].includes(digits.length) || (digits.startsWith('55') && [12, 13].includes(digits.length)) }
function validWhatsappMetaPhone (value) { return !value || /^\+55[1-9]\d[1-9]\d{7,8}$/.test(String(value).trim()) }
async function uploadAvatar (file) { if (!file) return; avatarLoading.value = true; const body = new FormData(); body.append('image', file); try { const { data } = await api.post('/auth/avatar', body); account.avatarUrl = ''; auth.updateUser(data.user); $q.notify({ type: 'positive', message: 'Foto profissional atualizada.' }) } catch (error) { $q.notify({ type: 'negative', message: error.response?.data?.message || 'Não foi possível enviar a foto.' }) } finally { avatarLoading.value = false } }
async function applyAvatarUrl () { if (!validAvatarUrl(account.avatarUrl)) return $q.notify({ type: 'negative', message: 'Informe uma URL HTTPS válida.' }); avatarLoading.value = true; try { const { data } = await api.put('/auth/avatar', { url: account.avatarUrl }); auth.updateUser(data.user); account.avatarUrl = data.user.avatar; $q.notify({ type: 'positive', message: 'Foto por URL atualizada.' }) } catch (error) { $q.notify({ type: 'negative', message: error.response?.data?.message || 'Não foi possível usar esta URL.' }) } finally { avatarLoading.value = false } }
function removeAvatar () { $q.dialog({ title: 'Remover foto?', message: 'Sua conta profissional voltará a mostrar suas iniciais.', cancel: true }).onOk(async () => { try { const { data } = await api.delete('/auth/avatar'); account.avatarUrl = ''; auth.updateUser(data.user); $q.notify({ message: 'Foto removida.', color: 'dark' }) } catch (error) { $q.notify({ type: 'negative', message: error.response?.data?.message || 'Não foi possível remover a foto.' }) } }) }
async function save () { saving.value = true; try { if (!account.name) throw new Error('Informe seu nome.'); if (!validPrimaryPhone(account.phone)) throw new Error('Informe o telefone principal completo, com DDD.'); if (!validWhatsappMetaPhone(account.whatsappMetaPhone)) throw new Error('O número alternativo do WhatsApp deve usar E.164 brasileiro, por exemplo +556181748795.'); if (reminders.enabled && !reminders.channels.length) throw new Error('Escolha ao menos um canal para os lembretes.'); const profilePayload = { ...profile.value, reminderSettings: { ...reminders } }; profile.value = (await api.put('/barber/profile', profilePayload)).data.profile; const [{ data: reminderData }, { data: accountData }] = await Promise.all([api.put('/barber/reminder-settings', reminders), api.patch('/auth/me', { name: account.name, phone: account.phone, whatsappMetaPhone: account.whatsappMetaPhone })]); Object.assign(reminders, reminderData.reminderSettings || reminderData.settings || reminderData); auth.updateUser(accountData.user); account.phone = accountData.user.phone || ''; account.whatsappMetaPhone = accountData.user.whatsappMetaPhone || ''; $q.notify({ type: 'positive', message: 'Configurações, perfil e lembretes salvos.' }) } catch (error) { $q.notify({ type: 'negative', message: error.response?.data?.message || error.message || 'Não foi possível salvar.' }) } finally { saving.value = false } }
onMounted(async () => { const { data } = await api.get('/barber/profile'); profile.value = data.profile; Object.assign(reminders, data.profile?.reminderSettings || {}); try { const response = await api.get('/barber/reminder-settings'); Object.assign(reminders, response.data.reminderSettings || response.data.settings || response.data) } catch { /* O perfil já contém os padrões durante uma atualização gradual. */ } })
</script>

<style scoped>
.reminder-card{overflow:hidden}.reminder-body{padding:0 22px 22px}.morning-reminder{margin-top:15px;padding:14px;display:grid;grid-template-columns:1fr 130px;align-items:center;gap:12px;border:1px solid #e1e5dd;border-radius:14px;background:#f7f9f4}.morning-reminder small{display:block;margin:2px 0 0 41px;color:#7f8881;font-size:9px}.reminder-toggles{margin-top:12px;display:grid;grid-template-columns:1fr 1fr;gap:8px}.reminder-toggles :deep(.q-toggle){padding:10px;border-radius:11px;background:#f6f7f3}.reminder-safety{margin-top:15px;padding:12px;display:flex;align-items:flex-start;gap:8px;border-radius:11px;background:#edf5e5;color:#5b6c50;font-size:9px;line-height:1.5}.reminder-safety .q-icon{font-size:19px;color:#64843f}@media(max-width:600px){.reminder-body{padding:0 15px 17px}.morning-reminder{grid-template-columns:1fr}.morning-reminder small{margin-left:0}.reminder-toggles{grid-template-columns:1fr}}
.professional-account-card{grid-column:1/-1}.professional-avatar-row{display:grid;grid-template-columns:110px minmax(0,1fr);gap:18px;padding:0 22px 12px;align-items:start}.professional-avatar{position:relative;width:96px}.professional-avatar>.q-btn{position:absolute;right:0;bottom:-2px}.professional-account-fields{display:grid;grid-template-columns:minmax(180px,.7fr) minmax(260px,1.3fr);gap:10px}.professional-avatar-actions{grid-column:1/-1;display:flex;flex-wrap:wrap;gap:7px}.avatar-safety{display:flex;gap:6px;margin:2px 22px 20px;color:#778178;font-size:9px}.avatar-safety .q-icon{font-size:17px;color:#61843c}.transparent-file{opacity:0;cursor:pointer}@media(max-width:700px){.professional-avatar-row{grid-template-columns:1fr;padding:0 15px 12px}.professional-avatar{margin:auto}.professional-account-fields{grid-template-columns:1fr}.professional-avatar-actions{grid-column:auto}.avatar-safety{margin:2px 15px 17px}}
</style>
