<template>
  <q-page class="dashboard-page builder-page" v-if="profile">
    <div class="page-intro builder-intro"><div><span class="page-overline">CRIADOR DE SITE</span><h1>Meu site</h1><p>Edite à esquerda e veja sua página ganhar forma ao lado.</p></div><div class="row q-gutter-sm"><q-btn :href="publicUrl" target="_blank" flat rounded no-caps label="Visualizar" icon="open_in_new" /><q-btn rounded unelevated color="dark" no-caps :label="profile.published ? 'Salvar e publicar' : 'Salvar rascunho'" icon="cloud_upload" :loading="saving" @click="save" /></div></div>
    <div class="builder-status"><div><span :class="['status-pulse', { off: !profile.published }]" /><b>{{ profile.published ? 'Publicado' : 'Rascunho' }}</b><span>{{ publicUrl }}</span></div><q-toggle v-model="profile.published" color="positive" :label="profile.published ? 'Site ativo' : 'Site inativo'" /></div>
    <div class="builder-layout">
      <section class="panel-card builder-controls">
        <q-tabs v-model="tab" dense no-caps align="left" active-color="dark" indicator-color="lime-6"><q-tab name="content" label="Conteúdo" /><q-tab name="design" label="Visual" /><q-tab name="sections" label="Blocos" /><q-tab name="settings" label="Link" /></q-tabs>
        <q-separator />
        <q-tab-panels v-model="tab" animated>
          <q-tab-panel name="content" class="builder-form"><label>CHAMADA PRINCIPAL</label><q-input v-model="profile.site.announcement" outlined rounded label="Aviso no topo do site" hint="Ex.: Agenda de agosto aberta" /><q-input v-model="profile.site.heroEyebrow" outlined rounded label="Texto acima do título" /><q-input v-model="profile.site.heroTitle" outlined rounded type="textarea" autogrow label="Título principal" counter maxlength="80" /><q-input v-model="profile.site.heroSubtitle" outlined rounded type="textarea" autogrow label="Texto de apoio" /><q-input v-model="profile.site.ctaLabel" outlined rounded label="Texto do botão" />
            <label>IMAGEM DE CAPA</label><div class="image-uploader" :style="profile.site.heroImage ? { backgroundImage: `url(${profile.site.heroImage})` } : {}"><div><q-icon name="add_photo_alternate" /><b>{{ profile.site.heroImage ? 'Trocar imagem' : 'Adicionar imagem' }}</b><small>PNG, JPG ou WebP · até 6 MB</small></div><q-file class="absolute-full transparent-file" borderless accept="image/*" @update:model-value="file => uploadImage(file, 'heroImage')" /></div>
            <label>BANNERS / CARROSSEL</label><div v-for="(banner, index) in profile.site.banners" :key="banner._id || index" class="builder-list-item builder-list-item--media"><div class="builder-media-thumb" :style="banner.image ? { backgroundImage: `url(${banner.image})` } : {}"><q-icon v-if="!banner.image" name="image" /><q-file class="absolute-full transparent-file" borderless accept="image/*" @update:model-value="file => uploadFor(file, url => { banner.image = url })" /></div><div class="col"><q-input v-model="banner.title" dense borderless label="Título do banner" /><q-input v-model="banner.subtitle" dense borderless label="Texto de apoio" /><q-input v-model="banner.link" dense borderless label="Link do botão" /></div><q-btn flat round icon="delete_outline" color="negative" @click="profile.site.banners.splice(index, 1)" /></div><q-btn outline rounded no-caps icon="add" label="Adicionar banner" @click="addBanner" />
          </q-tab-panel>
          <q-tab-panel name="design" class="builder-form"><label>IDENTIDADE VISUAL</label><div class="color-row"><q-input v-model="profile.site.primaryColor" outlined rounded label="Cor principal"><template #prepend><q-avatar size="24px" :style="{ background: profile.site.primaryColor }" /></template><template #append><q-popup-proxy cover transition-show="scale" transition-hide="scale"><q-color v-model="profile.site.primaryColor" /></q-popup-proxy></template></q-input><q-input v-model="profile.site.accentColor" outlined rounded label="Cor de destaque"><template #prepend><q-avatar size="24px" :style="{ background: profile.site.accentColor }" /></template><template #append><q-popup-proxy cover transition-show="scale" transition-hide="scale"><q-color v-model="profile.site.accentColor" /></q-popup-proxy></template></q-input></div><label>RODAPÉ</label><q-input v-model="profile.site.footerText" outlined rounded label="Texto do rodapé" /><q-input v-model="profile.site.socialLinks.instagram" outlined rounded label="Instagram" prefix="instagram.com/" /><q-input v-model="profile.site.socialLinks.tiktok" outlined rounded label="TikTok" prefix="tiktok.com/@" /></q-tab-panel>
          <q-tab-panel name="sections" class="builder-form"><div class="row items-center justify-between"><label class="q-mb-none">BLOCOS DA PÁGINA</label><q-btn flat round dense icon="add" @click="addSection" /></div><p class="builder-help">Combine história, destaques, galeria, depoimentos e chamadas para criar uma página completa.</p><div v-for="(section, index) in profile.site.sections" :key="section._id || index" class="section-editor"><div class="row items-center"><span class="drag-handle"><q-icon name="drag_indicator" /></span><q-select v-model="section.type" :options="sectionTypes" emit-value map-options dense borderless class="col" /><q-toggle v-model="section.visible" color="positive" /><q-btn flat round dense icon="delete_outline" @click="profile.site.sections.splice(index, 1)" /></div><div class="section-image-picker" :style="section.image ? { backgroundImage: `url(${section.image})` } : {}"><div><q-icon name="add_photo_alternate" /><span>{{ section.image ? 'Trocar imagem' : 'Adicionar imagem ao bloco' }}</span></div><q-file class="absolute-full transparent-file" borderless accept="image/*" @update:model-value="file => uploadFor(file, url => { section.image = url })" /></div><q-input v-model="section.title" outlined rounded dense :label="section.type === 'testimonial' ? 'Nome do cliente' : 'Título'" /><q-input v-model="section.text" outlined rounded dense type="textarea" autogrow :label="section.type === 'testimonial' ? 'Depoimento' : 'Texto'" /><div class="row q-col-gutter-sm"><q-input v-model="section.buttonLabel" class="col" outlined rounded dense :label="section.type === 'testimonial' ? 'Identificação' : 'Botão'" /><q-input v-if="section.type !== 'testimonial'" v-model="section.buttonLink" class="col" outlined rounded dense label="Link" /></div></div></q-tab-panel>
          <q-tab-panel name="settings" class="builder-form"><label>ENDEREÇO EXCLUSIVO</label><q-input v-model="profile.slug" outlined rounded label="URL do site" prefix="localhost:9000/" hint="Use apenas letras, números e hífens" /><q-input v-model="profile.businessName" outlined rounded label="Nome exibido" /><q-input v-model="profile.description" outlined rounded type="textarea" autogrow label="Descrição do negócio" />
            <label>MAPA E LOCALIZAÇÃO</label><p class="builder-help">No Google Maps, escolha Compartilhar → Incorporar um mapa e cole aqui o link ou o iframe completo.</p><q-input v-model="profile.site.locationMap.title" outlined rounded label="Título da localização" /><q-input v-model="profile.site.locationMap.subtitle" outlined rounded type="textarea" autogrow label="Texto de apoio" /><q-input v-model="profile.site.locationMap.embedUrl" outlined rounded type="textarea" autogrow label="URL ou iframe do mapa" placeholder='<iframe src="https://www.google.com/maps/embed?...">' /><div class="map-toggle-box"><div><q-toggle v-model="profile.site.locationMap.enabled" color="positive" label="Exibir no site" /><small>Adiciona uma seção ampla de localização.</small></div><div><q-toggle v-model="profile.site.locationMap.botEnabled" color="positive" label="Exibir no bot" /><small>O bot mostra o mapa ao responder “como chegar”.</small></div></div>
            <div class="publish-box"><q-icon name="public" /><div><b>Visibilidade do site</b><small>Quando inativo, seu link público fica indisponível.</small></div><q-toggle v-model="profile.published" color="positive" /></div></q-tab-panel>
        </q-tab-panels>
      </section>
      <aside class="builder-preview-wrap"><div class="preview-toolbar"><span><i class="red" /><i class="yellow" /><i class="green" /></span><div>{{ publicUrl }}</div><q-btn-toggle v-model="previewDevice" dense flat toggle-color="dark" :options="[{ icon: 'desktop_windows', value: 'desktop' }, { icon: 'smartphone', value: 'mobile' }]" /></div><div :class="['site-preview-stage', previewDevice]"><div class="site-mini" :style="{ '--mini-primary': profile.site.primaryColor, '--mini-accent': profile.site.accentColor }"><header><b>{{ profile.businessName }}</b><nav><span>Sobre</span><span>Serviços</span><button>{{ profile.site.ctaLabel }}</button></nav></header><section class="site-mini-hero" :style="profile.site.heroImage ? { backgroundImage: `linear-gradient(90deg, rgba(0,0,0,.8), rgba(0,0,0,.2)), url(${profile.site.heroImage})` } : {}"><span>{{ profile.site.heroEyebrow }}</span><h2>{{ profile.site.heroTitle }}</h2><p>{{ profile.site.heroSubtitle }}</p><button>{{ profile.site.ctaLabel }} →</button></section><section v-if="profile.site.banners.length" class="mini-banner"><small>DESTAQUE</small><b>{{ profile.site.banners[0].title || 'Seu banner em destaque' }}</b><span>{{ profile.site.banners[0].subtitle }}</span></section><section class="mini-about"><small>01 — NOSSA ESSÊNCIA</small><h3>{{ profile.site.sections[0]?.title || 'Mais que um corte.' }}</h3><p>{{ profile.site.sections[0]?.text || profile.description }}</p></section><section class="mini-services"><small>02 — SERVIÇOS</small><h3>Escolha sua experiência.</h3><div><article v-for="service in profile.services.slice(0, 3)" :key="service._id"><b>{{ service.name }}</b><span>R$ {{ Number(service.price).toFixed(0) }}</span></article></div></section><footer>{{ profile.site.footerText }}</footer></div></div></aside>
    </div>
  </q-page>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { useQuasar } from 'quasar'
import { api } from 'boot/axios'
const $q = useQuasar(); const profile = ref(null); const tab = ref('content'); const previewDevice = ref('desktop'); const saving = ref(false)
const sectionTypes = [{ label: 'Sobre', value: 'about' }, { label: 'Texto + imagem', value: 'feature' }, { label: 'Galeria', value: 'gallery' }, { label: 'Depoimento', value: 'testimonial' }, { label: 'Chamada final', value: 'cta' }]
const publicUrl = computed(() => `${window.location.origin}/${profile.value?.slug || ''}`)
function ensureSite () { profile.value.site.socialLinks ||= {}; profile.value.site.banners ||= []; profile.value.site.sections ||= []; profile.value.site.locationMap ||= { enabled: false, botEnabled: false, embedUrl: '', title: 'Onde estamos', subtitle: 'Trace sua rota e venha viver essa experiência.' } }
function addBanner () { profile.value.site.banners.push({ title: 'Uma experiência feita para você', subtitle: 'Reserve seu horário sem esperar.', image: '', link: `/${profile.value.slug}/agendar` }) }
function addSection () { profile.value.site.sections.push({ type: 'feature', title: 'Novo bloco', text: 'Conte aqui o que torna seu trabalho especial.', buttonLabel: '', buttonLink: '', visible: true }) }
async function uploadImage (file, field) { if (!file) return; const body = new FormData(); body.append('image', file); try { const { data } = await api.post('/barber/media', body); profile.value.site[field] = data.url; $q.notify({ type: 'positive', message: 'Imagem enviada e salva.' }) } catch (error) { $q.notify({ type: 'negative', message: error.response?.data?.message || 'Falha no upload.' }) } }
async function uploadFor (file, assign) { if (!file) return; const body = new FormData(); body.append('image', file); try { const { data } = await api.post('/barber/media', body); assign(data.url); $q.notify({ type: 'positive', message: 'Imagem adicionada ao bloco.' }) } catch (error) { $q.notify({ type: 'negative', message: error.response?.data?.message || 'Falha no upload.' }) } }
async function save () { saving.value = true; try { profile.value = (await api.put('/barber/profile', profile.value)).data.profile; ensureSite(); $q.notify({ type: 'positive', message: profile.value.published ? 'Site publicado com sucesso.' : 'Rascunho salvo.' }) } catch (error) { $q.notify({ type: 'negative', message: error.response?.data?.message || 'Não foi possível salvar.' }) } finally { saving.value = false } }
onMounted(async () => { profile.value = (await api.get('/barber/profile')).data.profile; ensureSite() })
</script>
