<template>
  <q-page class="dashboard-page admin-data-page">
    <div class="page-intro"><div><span class="page-overline">GESTÃO GLOBAL</span><h1>{{ config.title }}</h1><p>{{ config.subtitle }}</p></div><q-btn v-if="resource === 'users'" rounded unelevated color="dark" no-caps label="Novo usuário" icon="add" @click="openNew" /></div>
    <section class="panel-card data-card"><div class="data-toolbar"><q-input v-model="search" outlined rounded dense debounce="400" :placeholder="config.search" @update:model-value="load"><template #prepend><q-icon name="search" /></template><template #append><q-icon v-if="search" name="close" class="cursor-pointer" @click="search = ''; load()" /></template></q-input><q-select v-if="resource === 'users'" v-model="roleFilter" outlined rounded dense clearable :options="roleOptions" emit-value map-options label="Perfil" @update:model-value="load" /><q-select v-if="resource === 'appointments'" v-model="statusFilter" outlined rounded dense clearable :options="statusOptions" emit-value map-options label="Status" @update:model-value="load" /><q-btn flat round icon="refresh" @click="load" /></div>
      <q-table flat :rows="rows" :columns="columns" row-key="_id" :loading="loading" hide-pagination class="admin-table"><template #body-cell-user="props"><q-td :props="props"><div class="table-user"><q-avatar color="grey-3" text-color="dark" size="36px">{{ initials(props.row.name || props.row.user?.name) }}</q-avatar><div><b>{{ props.row.name || props.row.user?.name || props.row.customerName || 'Cliente balcão' }}</b><small>{{ props.row.email || props.row.user?.email || props.row.customerPhone }}</small></div></div></q-td></template><template #body-cell-active="props"><q-td :props="props"><q-badge rounded :color="props.value ? 'positive' : 'grey-5'" :label="props.value ? 'Ativo' : 'Inativo'" /></q-td></template><template #body-cell-published="props"><q-td :props="props"><q-badge rounded :color="props.value ? 'positive' : 'warning'" :label="props.value ? 'Publicado' : 'Rascunho'" /></q-td></template><template #body-cell-status="props"><q-td :props="props"><q-badge rounded :color="statusColor(props.value)" :label="statusLabel(props.value)" /></q-td></template><template #body-cell-createdAt="props"><q-td :props="props">{{ dateTime(props.value) }}</q-td></template><template #body-cell-start="props"><q-td :props="props">{{ dateTime(props.value) }}</q-td></template><template #body-cell-actions="props"><q-td :props="props"><q-btn v-if="resource !== 'bot-logs'" flat round dense icon="edit" @click="openEdit(props.row)" /><q-btn flat round dense icon="delete_outline" color="negative" @click="remove(props.row)" /></q-td></template></q-table>
      <div class="table-footer"><span>Mostrando {{ rows.length }} de {{ pagination.total }} registros</span><q-pagination v-model="pagination.page" :max="pagination.pages" direction-links color="dark" @update:model-value="load" /></div>
    </section>

    <q-dialog v-model="dialog"><q-card class="admin-dialog"><q-card-section class="dialog-title"><div><span>{{ editing ? 'EDITAR REGISTRO' : 'NOVO CADASTRO' }}</span><h3>{{ editing ? (form.name || form.businessName || form.serviceName) : 'Adicionar usuário' }}</h3></div><q-btn flat round icon="close" v-close-popup /></q-card-section><q-card-section class="form-stack" v-if="resource === 'users'"><q-input v-model="form.name" outlined rounded label="Nome completo" /><q-input v-model="form.email" outlined rounded label="E-mail" /><q-input v-model="form.phone" outlined rounded label="Telefone" mask="(##) #####-####" unmasked-value /><q-select v-model="form.role" outlined rounded :options="roleOptions" emit-value map-options label="Perfil" /><template v-if="form.role === 'BARBER'"><q-input v-model="form.businessName" outlined rounded label="Nome da barbearia" /><q-input v-model="form.slug" outlined rounded label="URL pública" prefix="/" /></template><q-input v-model="form.password" outlined rounded type="password" :label="editing ? 'Nova senha (opcional)' : 'Senha inicial'" /><q-toggle v-if="editing" v-model="form.active" label="Cadastro ativo" color="positive" /></q-card-section><q-card-section class="form-stack" v-else-if="resource === 'profiles'"><q-input v-model="form.businessName" outlined rounded label="Nome do negócio" /><q-input v-model="form.slug" outlined rounded label="URL pública" prefix="/" /><q-input v-model="form.address" outlined rounded label="Endereço" /><div class="row"><q-toggle v-model="form.active" label="Perfil ativo" color="positive" /><q-toggle v-model="form.published" label="Site publicado" color="positive" /></div></q-card-section><q-card-section class="form-stack" v-else-if="resource === 'appointments'"><q-input v-model="form.serviceName" outlined rounded label="Serviço" /><q-input v-model="form.start" outlined rounded type="datetime-local" label="Data e hora" stack-label /><q-select v-model="form.status" outlined rounded :options="statusOptions" emit-value map-options label="Status" /><q-input v-model="form.note" outlined rounded type="textarea" label="Observação" /></q-card-section><q-card-actions class="q-pa-md"><q-space /><q-btn flat rounded no-caps label="Cancelar" v-close-popup /><q-btn rounded unelevated color="dark" no-caps label="Salvar" :loading="saving" @click="save" /></q-card-actions></q-card></q-dialog>
  </q-page>
</template>

<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { useQuasar } from 'quasar'
import { api } from 'boot/axios'
const route = useRoute(); const $q = useQuasar(); const resource = computed(() => route.params.resource); const rows = ref([]); const loading = ref(false); const search = ref(''); const roleFilter = ref(null); const statusFilter = ref(null); const pagination = ref({ page: 1, pages: 1, total: 0 }); const dialog = ref(false); const editing = ref(null); const saving = ref(false); const form = reactive({})
const configs = { users: { title: 'Usuários', subtitle: 'Clientes e profissionais cadastrados na plataforma.', search: 'Buscar por nome, e-mail ou telefone' }, profiles: { title: 'Barbearias', subtitle: 'Perfis profissionais, URLs públicas e status de publicação.', search: 'Buscar negócio ou URL' }, appointments: { title: 'Agendamentos', subtitle: 'Todos os horários marcados em qualquer estabelecimento.', search: 'Buscar agendamento' }, 'bot-logs': { title: 'Interações do bot', subtitle: 'Perguntas, respostas e intenções registradas por barbearia.', search: 'Buscar nas conversas' } }; const config = computed(() => configs[resource.value] || configs.users)
const roleOptions = [{ label: 'Cliente', value: 'USER' }, { label: 'Barbeiro / salão', value: 'BARBER' }]; const statusOptions = [{ label: 'Confirmado', value: 'CONFIRMED' }, { label: 'Pendente', value: 'PENDING' }, { label: 'Concluído', value: 'COMPLETED' }, { label: 'Cancelado', value: 'CANCELLED' }]
const columnSets = { users: [{ name: 'user', label: 'Usuário', field: 'name', align: 'left' }, { name: 'role', label: 'Perfil', field: row => ({ USER: 'Cliente', BARBER: 'Barbeiro', ADMIN: 'Admin' }[row.role]), align: 'left' }, { name: 'active', label: 'Status', field: 'active' }, { name: 'createdAt', label: 'Cadastro', field: 'createdAt' }], profiles: [{ name: 'user', label: 'Negócio', field: 'businessName', align: 'left' }, { name: 'slug', label: 'URL', field: row => `/${row.slug}`, align: 'left' }, { name: 'published', label: 'Site', field: 'published' }, { name: 'active', label: 'Perfil', field: 'active' }], appointments: [{ name: 'user', label: 'Cliente', field: 'user', align: 'left' }, { name: 'serviceName', label: 'Serviço', field: 'serviceName', align: 'left' }, { name: 'profile', label: 'Barbearia', field: row => row.profile?.businessName, align: 'left' }, { name: 'start', label: 'Horário', field: 'start' }, { name: 'status', label: 'Status', field: 'status' }], 'bot-logs': [{ name: 'message', label: 'Pergunta', field: 'message', align: 'left' }, { name: 'response', label: 'Resposta', field: 'response', align: 'left' }, { name: 'profile', label: 'Barbearia', field: row => row.profile?.businessName, align: 'left' }, { name: 'intent', label: 'Intenção', field: 'intent' }, { name: 'createdAt', label: 'Data', field: 'createdAt' }] }
const columns = computed(() => [...(columnSets[resource.value] || columnSets.users), { name: 'actions', label: '', field: 'actions', align: 'right' }])
const initials = value => String(value || 'CM').split(' ').slice(0, 2).map(part => part[0]).join('').toUpperCase(); const dateTime = value => new Date(value).toLocaleString('pt-BR', { dateStyle: 'short', timeStyle: 'short' }); const statusLabel = value => statusOptions.find(item => item.value === value)?.label || value; const statusColor = value => ({ CONFIRMED: 'positive', PENDING: 'warning', COMPLETED: 'blue-grey', CANCELLED: 'negative' }[value])
async function load () { loading.value = true; try { const { data } = await api.get(`/admin/${resource.value}`, { params: { page: pagination.value.page, limit: 10, search: search.value, role: roleFilter.value, status: statusFilter.value } }); rows.value = data.data; pagination.value = data.pagination } finally { loading.value = false } }
function openNew () { editing.value = null; Object.keys(form).forEach(key => delete form[key]); Object.assign(form, { name: '', email: '', phone: '', password: '', role: 'USER', active: true, businessName: '', slug: '' }); dialog.value = true }
function openEdit (row) { editing.value = row; Object.keys(form).forEach(key => delete form[key]); Object.assign(form, JSON.parse(JSON.stringify(row))); if (form.start) form.start = form.start.slice(0, 16); dialog.value = true }
async function save () { saving.value = true; try { let payload = { ...form }; if (resource.value === 'profiles') payload = { businessName: form.businessName, slug: form.slug, address: form.address, active: form.active, published: form.published }; if (resource.value === 'appointments') payload = { serviceName: form.serviceName, start: form.start, status: form.status, note: form.note }; if (resource.value === 'users' && !editing.value) await api.post('/admin/users', payload); else await api.patch(`/admin/${resource.value}/${editing.value._id || editing.value.id}`, payload); $q.notify({ type: 'positive', message: 'Registro salvo.' }); dialog.value = false; load() } catch (error) { $q.notify({ type: 'negative', message: error.response?.data?.message || 'Não foi possível salvar.' }) } finally { saving.value = false } }
function remove (row) { $q.dialog({ title: 'Remover registro?', message: 'Os dados relacionados poderão ser removidos. Esta ação não pode ser desfeita.', cancel: true, persistent: true }).onOk(async () => { await api.delete(`/admin/${resource.value}/${row._id || row.id}`); $q.notify({ message: 'Registro removido.', color: 'dark' }); load() }) }
watch(resource, () => { pagination.value.page = 1; search.value = ''; load() }); onMounted(load)
</script>
